### ISSUE TITLE
InMemoryReadJournal functionality broken by Pekko v1.0.3

### ISSUE THREAD

**Issue by gclendinning02** [alstanchev/pekko-persistence-inmemory#10]
The latest 1.0.3 release for Pekko includes a change which prevents zero or negative intervals when scheduling tasks -> https://github.com/apache/pekko/pull/887.

The `InMemoryReadJournal` class makes use of `Source.tick` with a hardcoded interval of `0.seconds` in multiple places. This is causing the following stack trace:

```
java.lang.IllegalArgumentException: Task scheduled with [0] seconds delay, which means creating an infinite loop. The expected delay must be greater than 0.
[info] 	at org.apache.pekko.actor.LightArrayRevolverScheduler.checkPeriod(LightArrayRevolverScheduler.scala:227)
[info] 	at org.apache.pekko.actor.LightArrayRevolverScheduler.scheduleWithFixedDelay(LightArrayRevolverScheduler.scala:107)
[info] 	at org.apache.pekko.stream.impl.PhasedFusingActorMaterializer.scheduleWithFixedDelay(PhasedFusingActorMaterializer.scala:432)
[info] 	at org.apache.pekko.stream.stage.TimerGraphStageLogic.scheduleWithFixedDelay(GraphStage.scala:1740)
[info] 	at org.apache.pekko.stream.impl.fusing.GraphStages$TickSource$$anon$5.preStart(GraphStages.scala:255)
[info] 	at org.apache.pekko.stream.impl.fusing.GraphInterpreter.init(GraphInterpreter.scala:316)
[info] 	at org.apache.pekko.stream.impl.fusing.GraphInterpreterShell.init(ActorGraphInterpreter.scala:631)
[info] 	at org.apache.pekko.stream.impl.fusing.ActorGraphInterpreter.tryInit(ActorGraphInterpreter.scala:740)
[info] 	at org.apache.pekko.stream.impl.fusing.ActorGraphInterpreter.preStart(ActorGraphInterpreter.scala:789)
[info] 	at org.apache.pekko.actor.Actor.aroundPreStart(Actor.scala:558)
[info] 	at org.apache.pekko.actor.Actor.aroundPreStart$(Actor.scala:558)
[info] 	at org.apache.pekko.stream.impl.fusing.ActorGraphInterpreter.aroundPreStart(ActorGraphInterpreter.scala:729)
[info] 	at org.apache.pekko.actor.ActorCell.create(ActorCell.scala:654)
[info] 	at org.apache.pekko.actor.ActorCell.invokeAll$1(ActorCell.scala:523)
[info] 	at org.apache.pekko.actor.ActorCell.systemInvoke(ActorCell.scala:545)
[info] 	at org.apache.pekko.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:305)
[info] 	at org.apache.pekko.dispatch.Mailbox.run(Mailbox.scala:240)
[info] 	at org.apache.pekko.dispatch.Mailbox.exec(Mailbox.scala:253)
[info] 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
[info] 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
[info] 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
[info] 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
[info] 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```

Setting it to anything non-zero should resolve it.

**Comment by alstanchev** [comment]
Completed with #11
